apiVersion: v1
kind: Service

metadata:
  name: cloudops-nodejs-service

spec:
  type: NodePort

  selector:
    app: cloudops-nodejs

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
